services:
    nats-news-keyword-matcher-go:
        image: ghcr.io/heussd/nats-news-keyword-matcher-go:main
        build:
            context: .
            args:
                - MAIN=keyword-matcher
        environment:
            - 'NATS_SERVER=nats-server:4222'
            - 'FULLTEXTRSS_SERVER=http://fullfeedrss:80'
            - 'NEWS_STREAM_CONSUMER=default'
        deploy:
            replicas: 2
    nats:
        image: nats:2.10
        ports:
            - '4222:4222' # 4222 is for clients.
            - '8222:8222' # 8222 is an HTTP management port for information reporting.
            - '6222:6222' # 6222 is a routing port for clustering.
        command: '--jetstream'
    fullfeedrss:
        image: 'heussd/fivefilters-full-text-rss:latest'
        environment:
            # Leave empty to disable admin section
            - FTR_ADMIN_PASSWORD=
        ports:
            - '80:80'
