x-build: &build
    x-bake:
        platforms:
            - linux/amd64
            - linux/arm64

services:
    feed-feeder:
        build:
            <<: *build
            context: golang/.
            args:
                - MAIN=feed-feeder
    article-feeder:
        build:
            <<: *build
            context: golang/.
            args:
                - MAIN=article-feeder
    news-feeder:
        build:
            <<: *build
            context: golang/.
            args:
                - MAIN=news-feeder
    keyword-matcher:
        build:
            <<: *build
            context: golang/.
            args:
                - MAIN=keyword-matcher
    raindrop-integration:
        build:
            <<: *build
            context: golang/.
            args:
                - MAIN=raindrop-integration
    nats-indexer:
        build:
            <<: *build
            context: python/.
            target: nats-indexer
    search-mcp-server:
        build:
            <<: *build
            context: python/.
            target: search-mcp-server
