x-build: &build
    x-bake:
        platforms:
            - linux/amd64
            - linux/arm64

services:
    feed-feeder:
        build:
            <<: *build
            context: bash/.
    article-feeder:
        build:
            <<: *build
            context: golang/.
            args:
                - MAIN=article-feeder
    keyword-matcher:
        build:
            <<: *build
            context: golang/.
            args:
                - MAIN=keyword-matcher
    raindrop-integration:
        build:
            <<: *build
            context: golang/.
            args:
                - MAIN=raindrop-integration
