services:
  nats-server:
    image: nats:2.8
    ports:
      - "4222:4222" # 4222 is for clients.
      - "8222:8222" # 8222 is an HTTP management port for information reporting.
      - "6222:6222" # 6222 is a routing port for clustering.
    volumes:
      - "nats-persistence:/data"
    command: "--jetstream --http_port 8222 --store_dir /data"

  fullfeedrss:
    image: "heussd/fivefilters-full-text-rss:latest"
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=
    volumes:
      - "rss-cache:/var/www/html/cache"

  nats-rss-article-url-feeder:
    image: ghcr.io/heussd/nats-rss-article-url-feeder
    volumes:
      - type: bind
        source: ./urls.txt
        target: /urls.txt
        consistency: cached
        read_only: true
    environment:
      - "NATS_SERVER=nats-server:4222"
      - "URLS=/urls.txt"

  nats-news-keyword-matcher:
    image: ghrc.io/heussd/nats-news-keyword-matcher
    volumes:
      - type: bind
        source: ./keywords.txt
        target: /keywords.txt
        consistency: cached
        read_only: true
    environment:
      - "KEYWORDS_FILE:/keywords.txt"
      - "NATS_SERVER=nats-server:4222"
      - "FULLTEXTRSS_SERVER=http://fullfeedrss:80"
    deploy:
      replicas: 14

  nats-pocket-integration:
    image: ghcr.io/heussd/nats-pocket-integration
    environment:
      - "NATS_SERVER=nats-server:4222"
    secrets:
      - POCKET_ACCESS_TOKEN
      - POCKET_CONSUMER_KEY


volumes:
  rss-cache:
  nats-persistence:


secrets:
  POCKET_ACCESS_TOKEN:
    file: ./POCKET_ACCESS_TOKEN.txt
  POCKET_CONSUMER_KEY:
    file: ./POCKET_CONSUMER_KEY.txt
