services:
  nats-server:
    scale: 1
    image: docker.io/nats:2.9
    ports:
      - "4222:4222" # 4222 is for clients.
      - "8222:8222" # 8222 is an HTTP management port for information reporting.
      - "6222:6222" # 6222 is a routing port for clustering.
    volumes:
      - "./nats-persistence/:/data"
    command: "--jetstream --http_port 8222 --store_dir /data"

  fullfeedrss:
    scale: 2
    image: "heussd/fivefilters-full-text-rss:latest"
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=
    volumes:
      - "rss-cache:/var/www/html/cache"
    
  loadbalancer:
    scale: 1
    image: nginx
    volumes:
      - "./loadbalancer/nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
        - fullfeedrss
    ports:
        - '80:80'

  rss-article-url-feeder:
    scale: 2
    image: rss-article-url-feeder
    build: rss-article-url-feeder/.
    volumes:
      - type: bind
        source: ./urls.txt
        target: /urls.txt
        consistency: cached
        read_only: true
    environment:
      - "NATS_SERVER=nats-server:4222"
      - "URLS=/urls.txt"
    restart: always

  keyword-matcher-go:
    scale: 5
    image: keyword-matcher-go
    build: keyword-matcher-go/.
    volumes:
      - type: bind
        source: ./keywords.txt
        target: /keywords.txt
        consistency: cached
        read_only: true
    environment:
      - "KEYWORDS_FILE:/keywords.txt"
      - "NATS_SERVER=nats-server:4222"
      - "FULLTEXTRSS_SERVER=http://loadbalancer:80"
  
  keyword-matcher-python:
    scale: 0
    image: keyword-matcher-python
    build: keyword-matcher-python/.
    volumes:
      - type: bind
        source: ./keywords.txt
        target: /keywords.txt
        consistency: cached
        read_only: true
    environment:
      - "KEYWORDS_FILE:/keywords.txt"
      - "NATS_SERVER=nats-server:4222"
      - "FULLTEXTRSS_SERVER=http://fullfeedrss:80"

  pocket-integration:
    scale: 1
    image: pocket-integration
    build: pocket-integration/.
    environment:
      - "NATS_SERVER=nats-server:4222"
    secrets:
      - POCKET_ACCESS_TOKEN
      - POCKET_CONSUMER_KEY


volumes:
  rss-cache:


secrets:
  POCKET_ACCESS_TOKEN:
    file: ./POCKET_ACCESS_TOKEN.txt
  POCKET_CONSUMER_KEY:
    file: ./POCKET_CONSUMER_KEY.txt
