services:   
  rss-article-url-feeder-go:
    image: ghcr.io/heussd/nats-news-analysis/rss-article-url-feeder-go:latest
    build:
      context: rss-article-url-feeder-go/.
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64

  rss-article-url-feeder-python:
    image: ghcr.io/heussd/nats-news-analysis/rss-article-url-feeder-python
    build:
      context: rss-article-url-feeder-python/.
      cache_from:
        - ghcr.io/heussd/nats-news-analysis/rss-article-url-feeder-python
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64

  keyword-matcher-go:
    image: ghcr.io/heussd/nats-news-analysis/keyword-matcher-go
    build:
      context: keyword-matcher-go/.
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
  
  keyword-matcher-python:
    image: ghcr.io/heussd/nats-news-analysis/keyword-matcher-python
    build:
      context: keyword-matcher-python/.
      cache_from:
        - ghcr.io/heussd/nats-news-analysis/keyword-matcher-python
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64

  pocket-integration:
    image: ghcr.io/heussd/nats-news-analysis/pocket-integration
    build:
      context: pocket-integration/.
      cache_from:
        - ghcr.io/heussd/nats-news-analysis/pocket-integration
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
