{
 "title": "News Analysis",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Average Matching Time",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(\n{compose_project=\"nats-news-analysis\"}\n| json\n| message = \"Analysis complete\"\n| unwrap keyword_matching_duration_ms\n[1s]\n) by (service)"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 14, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (match, service) (rate(\n{compose_project=\"nats-news-analysis\"}\n| json\n| message = \"Analysis complete\"\n[1h]\n))"
    }
   ]
  },
  {
   "title": "Matching / m",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (service) (rate(\n{compose_project=\"nats-news-analysis\"}\n| json\n| message = \"Analysis complete\"\n[1m]\n))"
    }
   ]
  },
  {
   "title": "Processed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "count by (match, service) (rate(\n{compose_project=\"nats-news-analysis\"}\n| json\n| message = \"Analysis complete\"\n[1h]\n))"
    },
    {
     "expr": "jetstream_stream_total_messages{stream_name=\"article-urls\"}",
     "legendFormat": "article_urls"
    },
    {
     "expr": "jetstream_stream_total_messages{stream_name=\"match-urls\"}",
     "legendFormat": "match_urls"
    }
   ]
  },
  {
   "title": "1h Thoughput",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (container_name) (rate(\n{compose_project=\"nats-news-analysis\"}\n| json\n| message = \"Analysis complete\"\n[1h]\n))"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "avg_over_time(\n{compose_project=\"nats-news-analysis\"}\n| json\n| message = \"Analysis complete\"\n| unwrap keyword_matching_duration_ms\n[1s]\n) by (service)"
    }
   ]
  }
 ]
}