version: "3.7"

services:
  nats-news-keyword-matcher-python:
    image: ghcr.io/heussd/nats-news-keyword-matcher-python
    build: .
    volumes:
      - type: bind
        source: ./keywords.txt
        target: /keywords.txt
        consistency: cached
        read_only: true
    environment:
      - "KEYWORDS_FILE:/keywords.txt"
      - "NATS_SERVER=nats-server:4222"
  nats-server:
    image: nats:2.8
    ports:
      - "4222:4222" # 4222 is for clients.
      - "8222:8222" # 8222 is an HTTP management port for information reporting.
      - "6222:6222" # 6222 is a routing port for clustering.
    command: "--jetstream"
  fullfeedrss:
    image: "heussd/fivefilters-full-text-rss:latest"
    environment:
      # Leave empty to disable admin section
      - FTR_ADMIN_PASSWORD=
    ports:
      - "80:80"
