apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://host.docker.internal:3100
    version: 1
    editable: false
    isDefault: true
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: 'http://prometheus:9090'
    isDefault: false
    version: 1
    editable: true