services:
  nats-server:
    image: nats:2.8
    ports:
      - "4222:4222" # 4222 is for clients.
      - "8222:8222" # 8222 is an HTTP management port for information reporting.
      - "6222:6222" # 6222 is a routing port for clustering.
  nats-pocket-integration:
    image: ghcr.io/heussd/nats-pocket-integration
    build: .
    environment:
      - "NATS_SERVER=nats-server:4222"
    secrets:
      - POCKET_ACCESS_TOKEN
      - POCKET_CONSUMER_KEY

secrets:
  POCKET_ACCESS_TOKEN:
    file: ./POCKET_ACCESS_TOKEN.txt
  POCKET_CONSUMER_KEY:
    file: ./POCKET_CONSUMER_KEY.txt
