## Search
POST {{AI_SEARCH_ENDPOINT}}/indexes('index')/docs/search.post.search?api-version={{AI_SEARCH_API_VERSION}}   HTTP/1.1
Content-Type: application/json
api-key: {{AI_SEARCH_API_KEY}}
{
    "search": "schneller",
    "select": "title",
    "facets": ["date", "language", "author", "baseUrl"]
}
?? status == 200

### Add
POST {{AI_SEARCH_ENDPOINT}}/indexes('index')/docs/search.index?api-version={{AI_SEARCH_API_VERSION}}
Content-Type: application/json
api-key: {{AI_SEARCH_API_KEY}}
{
  "value": [
    {
      "@search.action": "mergeOrUpload",
      "docId": "12",
      "name": "test"
    },
    {
      "@search.action": "mergeOrUpload",
      "docId": "13",
      "name": "test"
    }
  ]
}

### Create index
POST {{AI_SEARCH_ENDPOINT}}/indexes?api-version={{AI_SEARCH_API_VERSION}}  HTTP/1.1
Content-Type: application/json
api-key: {{AI_SEARCH_API_KEY}}
{{
    test.status(201)
}}
{
    "name": "index",
    "fields": [
        {"name": "id", "type": "Edm.String", "key": true, "filterable": true},
        {"name": "title", "type": "Edm.String", "searchable": true, "filterable": true, "retrievable": true, "sortable": true, "facetable": true},
        {"name": "excerpt", "type": "Edm.String", "searchable": true, "filterable": true, "retrievable": true, "sortable": true, "facetable": true},
        {"name": "date", "type": "Edm.DateTimeOffset", "searchable": false, "filterable": true, "retrievable": true, "sortable": true, "facetable": true},
        {"name": "author", "type": "Edm.String", "searchable": true, "filterable": true, "retrievable": true, "sortable": true, "facetable": true},
        {"name": "language", "type": "Edm.String", "searchable": true, "filterable": true, "retrievable": true, "sortable": true, "facetable": true},
        {"name": "url", "type": "Edm.String", "searchable": true, "filterable": true, "retrievable": true, "sortable": true, "facetable": true},
        {"name": "baseUrl", "type": "Edm.String", "searchable": true, "filterable": true, "retrievable": true, "sortable": true, "facetable": true},
        {"name": "content", "type": "Edm.String", "searchable": true, "filterable": false, "retrievable": true, "sortable": false, "facetable": false},
        {
            "name": "vector",
            "type": "Collection(Edm.Single)",
            "searchable": true,
            "retrievable": false,
            "stored": false,
            "dimensions": 384,
            "vectorSearchProfile": "vector-profile-1"
        }
        ],
        "vectorSearch": {
        "algorithms": [
            {
                "name": "hnsw-1",
                "kind": "hnsw",
                "hnswParameters": {
                    "m": 4,
                    "efConstruction": 400,
                    "efSearch": 500,
                    "metric": "cosine"
                }
            }
        ],
        "profiles": [
            {
                "name": "vector-profile-1",
                "algorithm": "hnsw-1"
            }
        ]
    }
}


## Delete an index
DELETE {{AI_SEARCH_ENDPOINT}}/indexes/index?api-version={{AI_SEARCH_API_VERSION}}
    Content-Type: application/json
    api-key: {{AI_SEARCH_API_KEY}}
    ?? status == 204


## List Indexes
GET {{AI_SEARCH_ENDPOINT}}/indexes?api-version=2025-09-01  HTTP/1.1
  Content-Type: application/json
  api-key: {{AI_SEARCH_API_KEY}}
    ?? status == 200