services:
  nats-server:
    image: nats:2.8
    ports:
      - "4222:4222" # 4222 is for clients.
      - "8222:8222" # 8222 is an HTTP management port for information reporting.
      - "6222:6222" # 6222 is a routing port for clustering.
    command: "--jetstream"
  nats-rss-article-url-feeder:
    image: ghcr.io/heussd/nats-rss-article-url-feeder
    build: .
    environment:
      - "NATS_SERVER=nats-server:4222"
