services:
    nats-server:
        image: nats:2.9
        ports:
            - '4222:4222' # 4222 is for clients.
            - '8222:8222' # 8222 is an HTTP management port for information reporting.
            - '6222:6222' # 6222 is a routing port for clustering.
        command: '--jetstream'
    nats-raindrop--integration:
        image: ghcr.io/heussd/nats-news-analysis/raindrop-integration:latest
        build: .
        environment:
            - 'NATS_SERVER=nats-server:4222'
        env_file:
            - .env
